apiVersion: v1
kind: Namespace
metadata: 
  name: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: oa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
  labels:
    sec: p1
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      sec: p1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1  
  minReadySeconds: 10
  template:
    metadata:
       labels:
         sec: p1
    spec:
      containers:
      - name: c1
        image: nigelpoulton/k8sbook:text-prod
        ports:
        - containerPort: 8080  
---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: d1
   labels:
     sec: o1
   namespace: oa
spec:
  replicas: 4
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      sec: o1
  template:
    metadata:
      labels:
        sec: o1
    spec:
      containers:
      - name: c1
        image: nigelpoulton/k8sbook:text-dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: s1
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    sec: p1
---
apiVersion: v1
kind: Service
metadata:
  name: s1
  namespace: oa
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    sec: o1
---
apiVersion: v1
kind: Pod
metadata:
  name: jump
  namespace: prod
spec:
  containers:
  - name: c3
    image: ubuntu:latest
    tty: true
    stdin: true      
