apiVersion: apps/v1
kind: Deployment
metadata:
 name: ngix-dpl                 
 labels:
   app: nginx                     
spec:
 replicas: 3                    
 selector:                      
     matchLabels:                
        app: nginx               
 template:                      
   metadata:
     labels:                    
       app: nginx               
   spec:                        
     containers:                
     - name: nginx-pod          
       image: nginx:1.17.4      
       ports:
       - containerPort: 80      
