apiVersion: v1
kind: Pod
metadata: 
  name: pe1
  labels:
    country: ind
spec:
  volumes:
  - name: http
    emptyDir: {}
  containers:
  - name: c87
    image: ubuntu:latest 
    volumeMounts:
    - name: http
      mountPath: /var/htdocs
  - name: c88
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: http
      mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: s50
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31010
    protocol: TCP
  selector:
    country: ind
  

