apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 3
  selector:
      country: china
  template:
    metadata:
      labels:
        country: china
    spec:
      containers:
      - name: c11
        image: ubuntu:latest
        command: ["/bin/sleep","3650d"]
