apiVersion: v1
kind: Service
metadata:
  name: s1
  labels:
    sec: prod
    dep: infra
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30090
    protocol: TCP
  selector:
    sec: prod
    dep: infra
 
