apiVersion: v1
kind: Service
metadata:
  name: s2
  labels:
    sec: oa
    dep: infra1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30099
    protocol: TCP
  selector:
    sec: oa
    dep: infra1
 
